version: "3.7"
services:
  amazoncorretto_11_ubuntu_22.04:
    image: sa201/amazoncorretto:11-ubuntu-22.04
    build:
      dockerfile: jdk/amazon_corretto/11/Dockerfile
  opencv_4.7.0_ubuntu_22.04:
    image: sa201/opencv:4.7.0-ubuntu-22.04
    build:
      dockerfile: opencv/4.7.0/Dockerfile
      args:
        BASE_IMAGE: sa201/amazoncorretto:11-ubuntu-22.04
    depends_on:
      - amazoncorretto_11_ubuntu_22.04

